##Personal Information
name = input ("Enter your full name: ")
gender = input ("Enter your gender (male/female/prefer not to say): ")
age = int (input("Enter your age: "))
bday = input ("Enter your birthdate (mm/dd/yyyy): ")
uni = input ("Name of University: ")
number = int (input ("Enter your mobile number: "))
mother_name = input ("Enter your mother's name: ")
father_name = input ("Enter your father's name: ")
address = input ("Enter your address: ")
email = input ("Enter you email address: ")

print ("Name: ", name)
print ("Gender: ", gender) 
print ("Age: ", age) 
print ("Birthdate: ", bday)
print ("School: ", uni) 
print ("Mobile Number: ", number)
print ("Mother's Name: ", mother_name) 
print ("Father's Name: ", father_name) 
print ("Address: ", address) 
print ("Email: ", email)